name: .NET

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --no-self-contained
    - name: Publish Repackinator
      run: dotnet publish ./Repackinator/Repackinator.csproj -c Release -p:DebugType=None -p:DebugSymbols=false
    - name: Publish RepackinatorUI - Windows
      run: dotnet publish -r win-x64 ./RepackinatorUI/RepackinatorUI.csproj -c Release --self-contained true -p:DebugType=None -p:DebugSymbols=false
      #run: dotnet publish ./RepackinatorUI/RepackinatorUI.csproj -c Release -p:DebugType=None -p:DebugSymbols=false
    - name: Publish RepackinatorUI - Linux
      run: dotnet publish -r linux-x64 ./RepackinatorUI/RepackinatorUI.csproj -c Release --self-contained true -p:DebugType=None -p:DebugSymbols=false
    - run: ls -R
    - name: Upload Repackinator Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Repackinator
        path: ${{ github.workspace }}/Repackinator/Repackinator/bin/Release/net6.0/win-x64/publish/
    - name: Upload RepackinatorUI Build Artifact - Windows
      uses: actions/upload-artifact@v2
      with:
        name: RepackinatorUI
        path: ${{ github.workspace }}/Repackinator/RepackinatorUI/bin/Release/net6.0/win-x64/publish/
        if-no-files-found: error
    - name: Upload RepackinatorUI Build Artifact - Linux
      uses: actions/upload-artifact@v2
      with:
        name: RepackinatorUI
        path: ${{ github.workspace }}/Repackinator/RepackinatorUI/bin/Release/net6.0/linux-x64/publish/
        if-no-files-found: error
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
